services:
  obsidian:
    networks:
      - proxy
    image: lscr.io/linuxserver/obsidian:latest
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FM_HOME=/config/data
    volumes:
      - /var/obsidian:/config
    ports:
      - 3000:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: unless-stopped

  tools:
    image: corentinth/it-tools:latest
    restart: unless-stopped
    ports:
        - 3001:80
    environment:
        - UID=1000
        - GID=1000
    networks:
      - proxy

  simple:
    image: 'yeasy/simple-web:latest'
    ports:
        - '8000:80'
    tty: true
    stdin_open: true
    networks:
      - proxy

  haproxy:
    image: haproxy:latest
    ports:
      - 80:80
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - proxy

  ddns:
    build: ./ddns
    volumes:
      - ./ddns/config.yml:/ddns/config.yml

networks:
  proxy:
    name: proxy